在主README里面添加基本主张和目的 / Add principle and purpose of this repository
996icu/996.ICU pull request #24743
Opened 2019-03-30 17:52 UTC by yyrdl

目前的 README 里面并没有清晰地给出我们的主张 和 目的， 也未对这次倡议 进行定性。
 
导致该项目很容易被人误解，比如python 之父居然在社交网站建议我们革命，这是万万不妥的； 也容易被别有用心的人利用。

因此草拟了几条，可能不完备，语言表述和英文翻译可能也有问题，抛砖引玉吧

2019-03-30 18:39 UTC, KnifeOfLife commented
支持，我也觉得应当明确我们的主张和目的。目前项目里虽然已经阐述了咱们程序员的处境和相关的法律法规，但是没有申明我们的主张和最终目标。我们反对的究竟是996制度，还是反对实行了996制度但是没有给足报酬的公司？我们的最终目的是想披露国内的加班环境，还是制定996公司黑名单，还是目前看起来很有想法的license。这些不但外国人不清楚，甚至连咱们自己人也不清楚。只有统一了方向，消灭分歧，统一战线，劲往一处使，才能实现我们的目的。

2019-03-30 20:21 UTC, Menee commented
The Principle and Purpose Of 996.ICU 
---

 * It is not a politic motivation.We are the staunch supporters of labour law. we ask employers to respect labor rights.

 * 这里知道有语法问题但是不知道怎么改比较好。We want to create  licenses that protect labor rights.
(开源意味着允许邪恶用途（opensource.org），以及不止一个协议（如类MIT，类Apache，类GPL协议）)（labor rights，差不多是个专有名词了）

 * We welcome all suggestions and advocate mature and responsible speech.（复数是演讲，言论不可数）（其实觉得这句话还是有问题）

 * 996.ICU is initiatively initiated by Chinese IT industry practitioners. We welcome people from other fields and other countries to join the discussion.

 * At present, 996 ICU License is immature. We hope for the help from professionals.

我把我觉得有问题的地方改了一下。当然我很菜不太会改。
这个页面主要是给外国人看的。怕的是英语母语者理解的了我们的中式英语，但其他国家的人不理解。


说实在我觉得到现在为止，996.icu做了很多有益的尝试。但我觉得我们做的很多东西还有些幼稚。

如果有条件，可以聘请律师来出谋划策，维护动者权利。

希望理性对待我这条留言，不要人身攻击。
我是一个和996.icu利益相关的CS本科生。

2019-03-30 21:35 UTC, SkyKn1ght approved these changes

2019-03-31 00:45 UTC, torchlard commented
我覺得首先要聲明這個運動不是革命，而是根據法律正當維權，免得外國人誤會

2019-03-31 00:54 UTC, bofeiw approved these changes

2019-03-31 01:45 UTC, guokaihappy commented
个人觉得，先把我们的观点表达清楚，统一内部思想。1:通过该项目，希望政府相关部门引起重视，改善国内工作环境，约束公司收敛违法行为，落实劳动法对员工利益保护，加大对违法公司的惩罚力度。2:统计违反劳动法公司黑名单，便于大伙找工作被坑，落去虎口。3:制定内部对于违规公司的处罚策略，比如禁止996公司免费使用开源框架，由于主流开源框架都是国外开发，争取获得外国同行的支持，帮助员工处理与996公司的劳务纠纷

2019-03-31 02:42 UTC, yyrdl commented
> ## The Principle and Purpose Of 996.ICU
> * It is not a politic motivation.We are the staunch supporters of labour law. we ask employers to respect labor rights.
> * 这里知道有语法问题但是不知道怎么改比较好。We want to create  licenses that protect labor rights.
>   (开源意味着允许邪恶用途（opensource.org），以及不止一个协议（如类MIT，类Apache，类GPL协议）)（labor rights，差不多是个专有名词了）
> * We welcome all suggestions and advocate mature and responsible speech.（复数是演讲，言论不可数）（其实觉得这句话还是有问题）
> * 996.ICU is initiatively initiated by Chinese IT industry practitioners. We welcome people from other fields and other countries to join the discussion.
> * At present, 996 ICU License is immature. We hope for the help from professionals.
> 
> 我把我觉得有问题的地方改了一下。当然我很菜不太会改。
> 这个页面主要是给外国人看的。怕的是英语母语者理解的了我们的中式英语，但其他国家的人不理解。
> 
> 说实在我觉得到现在为止，996.icu做了很多有益的尝试。但我觉得我们做的很多东西还有些幼稚。
> 
> 如果有条件，可以聘请律师来出谋划策，维护动者权利。
> 
> 希望理性对待我这条留言，不要人身攻击。
> 我是一个和996.icu利益相关的CS本科生。

我也觉得英文部分有问题，感谢你的建议，正在找英语好的人改

2019-03-31 03:16 UTC, IlliosAcademy requested changes
Fix grammar error and improve sentences.

2019-03-31 03:16 UTC, IlliosAcademy commented on README.md
> +The principle and purpose Of this repository!
The principle and purpose of this repository!

2019-03-31 03:16 UTC, IlliosAcademy commented on README.md
> +* this is not a politic activity,we are the staunch supporters of labour law. we ask employers to respect the legitimate rights and interests of employees.
This is not a political activity, we are the staunch supporters of labour law. We ask employers to respect the legitimate rights and interests of employees.

2019-03-31 03:16 UTC, IlliosAcademy commented on README.md
> +* this is not a politic activity,we are the staunch supporters of labour law. we ask employers to respect the legitimate rights and interests of employees.
This is not a political activity, we are the staunch supporters of labour law. We ask employers to respect the legitimate rights and interests of employees.

2019-03-31 03:16 UTC, IlliosAcademy commented on README.md
> +* 996.ICU is an initiative initiated by IT practitioners. We welcome people from other fields and other countries to join the discussion.
996.ICU is an initiative initiated by IT practitioners. We welcome people from all fields and all countries to join the discussion.

2019-03-31 03:23 UTC, yyrdl commented on README.md
> +* 996.ICU is an initiative initiated by IT practitioners. We welcome people from other fields and other countries to join the discussion.
额，这个conversation 没用过，朋友，你修正了英文翻译吗？ 我找不到呀？ T_T

2019-03-31 03:28 UTC, merged