Update blacklist.md
996icu/996.ICU pull request #24787
Opened 2019-03-31 11:38 UTC by uDp30Z4w

2019-03-31 11:44 UTC, bofeiw requested changes

2019-03-31 11:44 UTC, bofeiw commented on blacklist/blacklist.md
> +|深圳|[华为](https://www.huawei.com/cn/)|2010年8月|9106|[华为：“自愿”的奋斗者协议](http://focus.news.163.com/10/0921/15/6H460OOP00011SM9.html)|
这里其实新闻报道是10年9月

2019-03-31 12:33 UTC, rubyrubyrose commented
我支持965工作模式，欢迎进入965工作模式---->>>http://965.ICU/

2019-03-31 13:51 UTC, pjzhong commented
能把@rubyrubyrose给禁了吗？

2019-03-31 13:55 UTC, 996icu commented
> 能把@rubyrubyrose给禁了吗？

已block，这个公司的人不停换账号过来打广告

2019-03-31 13:55 UTC, merged

2019-04-01 10:27 UTC, ShuaiShuaiLee commented
> 
> 
> > 能把@rubyrubyrose给禁了吗？
> 
> 已block，这个公司的人不停换账号过来打广告

有人说，你被请去喝茶了？你没有收到政治压力或者其他公司的压力吧！我们可是和平抗议！