996license 开源项目联盟列表
996icu/996.ICU pull request #24788
Opened 2019-03-31 12:29 UTC by CN-YUANYU

996license 开源项目联盟列表

2019-03-31 12:33 UTC, rubyrubyrose commented
我支持965工作模式，欢迎进入965工作模式---->>>http://965.ICU/

2019-03-31 12:33 UTC, ShuaiShuaiLee commented
这个协议要是搞成功了，都获得了主流开源软件支持的话！那将在互联网史上写下浓重一笔！

2019-03-31 12:59 UTC, bofeiw requested changes
列表格式不太对，建议修改

2019-03-31 13:01 UTC, bofeiw commented
而且，这样一个列表后期可能会很长，不建议放到主README里面

2019-03-31 13:05 UTC, CN-YUANYU commented
@bofeiw 好的

2019-03-31 13:13 UTC, CN-YUANYU commented
@bofeiw 已经更新

2019-03-31 13:35 UTC, fengshenyuan commented
* README 里面放列表不太合适，放列表的链接更好
* 已有几个类似的PR ref https://github.com/996icu/996.ICU/pulls?utf8=%E2%9C%93&q=supporting
* repo主创者应该有一些自己的考虑和计划，且稍安勿躁，不必提重复的PR.

2019-03-31 14:01 UTC, 996icu commented
> * README 里面放列表不太合适，放列表的链接更好
> * 已有几个类似的PR ref https://github.com/996icu/996.ICU/pulls?utf8=%E2%9C%93&q=supporting
> * repo主创者应该有一些自己的考虑和计划，且稍安勿躁，不必提重复的PR.

主要原因是考虑到现在license还是草案阶段，可能存在法律风险。再完善一些后，会加入一个项目列表的。

2019-03-31 15:27 UTC, BestiOSDev commented
我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班  工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996

2019-03-31 15:42 UTC, bofeiw commented
> 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996

同意。自己的权利要自己去争取，而不是妥协**卑微地** 迁就，**懦弱地**退缩。正式那些为了为己在老板面前装好人的奸邪小人的迁就那些老板，造成了加班制度陷入了一个恶性循环：你不加班，你滚，有的是奸邪小人。同时，一个公司实行加班制度，其他公司也会效仿。

说白了还是廉价劳动力供远大于求

2019-03-31 15:47 UTC, landy8530 commented
这种协议必须顶上去！

2019-03-31 21:08 UTC, zxkjack123 commented on README.md
> +- this is not a politic activity,we are the staunch supporters of labour law. we ask employers to respect the legitimate rights and interests of employees.
```suggestion
- this is not a politic activity, we are the staunchest supporters of labour law. We ask employers to respect the legitimate rights and interests of employees.
```

2019-03-31 21:11 UTC, zxkjack123 commented on README.md
> +- From closed source to open source is a great progress, from open source to emphasizing the protection of labor rights and interests at the same time will also be an another great progress. We want
```suggestion
- From the closed source to open source is a great progress, from open source to emphasizing the protection of labors' rights and interests at the same time will also be a great progress. We want to create an open source software license that protects workers' rights and interests.
```

2019-03-31 21:43 UTC, Czxck001 commented
@CN-YUANYU Shall we put it in English or at least provide an version translated in English? That will make it more influential.

2019-04-01 00:16 UTC, pjjr123 commented
中国程序员 
基本都是些农民大学生
人多的跟蟑螂一样
你不做后面几万个人排队
最后的结果 就是996 007
农民的原罪
也是中国问题的原罪
就是农民太多 
而且劣性繁殖

2019-04-01 00:44 UTC, wangjianlin996icu commented
希望某些外界垃圾(pjjr123)，不会影响到大家的心情

2019-04-01 00:46 UTC, Lry0504 commented
> 希望某些外界垃圾(pjjr123)，不会影响到大家的心情

+1，谁不是农民的孩子~

2019-04-01 01:07 UTC, pjjr123 commented
很多人骂我 但是你们想一下
我说的是不是事实
社会资源总量不变
低端人口大量劣性繁殖
最后就是生存环境恶化

你们搞的什么996.icu
最后的结果
就是Github被长城防火墙封杀

2019-04-01 01:24 UTC, asche910 commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

你可闭嘴吧，优秀bi。而且为啥不敢用大号呢

2019-04-01 01:24 UTC, 704826318 commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

你难道不是农民演化过来的？照你这么说你自己也是劣性的后代。

2019-04-01 01:29 UTC, hynanan commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

低端人口？劣性繁殖？生存恶化？我算是知道想文学作品里的大反派是怎么来的了，这种自恃清高的人真的是难得一遇，希望贵为“精英“的您在拥有无限手套之时，轻声响指，好让“低端”人口无声消失，让您能在展现男人雄风

2019-04-01 01:31 UTC, chenlei65368 commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

别忘了，你就是从低端人口过来的，你现在就忘掉了你的身份了？

2019-04-01 01:37 UTC, jacksplwxy commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

有道理，但别歧视农民哦，这只是阶级的局限性而已

2019-04-01 01:52 UTC, CN-YUANYU commented
@pjjr123 首先你要知道996是违法的， 无论你做什么事情，请遵从中国法律

2019-04-01 02:03 UTC, 417401901 commented
那个小号。好像在每个底下的话都是一样的。不要理就好了

2019-04-01 02:06 UTC, chenlushun commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

@pjjr123 没有调查就没有发言权，为什么这么主观的下这么多结论，你倒是拿出一些论据出来呀？不要妄自菲薄

2019-04-01 02:07 UTC, kattgu7 commented
> > * README 里面放列表不太合适，放列表的链接更好
> > * 已有几个类似的PR ref https://github.com/996icu/996.ICU/pulls?utf8=%E2%9C%93&q=supporting
> > * repo主创者应该有一些自己的考虑和计划，且稍安勿躁，不必提重复的PR.
> 
> 主要原因是考虑到现在license还是草案阶段，可能存在法律风险。再完善一些后，会加入一个项目列表的。

我个人觉得可以先用起来？毕竟现在的任务是要让更多的人知道支持这件事，draft可能有些没考虑到不够全面，或者可以钻空子的地方，但是基本上问题不大。MIT或者UIUC/NCSA之类的license也基本上就是简短的两三段，里面肯定也有不够全面的地方，如果真的要写一个完全没有漏洞的协议，这个时间可能是一两年。

2019-04-01 02:08 UTC, asuradagsx1 commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

照这说法可以学灭霸，打个响指就解决了咯？自欺欺人的做法

2019-04-01 02:18 UTC, NethenCyjCN commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

nmsl

2019-04-01 02:22 UTC, yzuwangfeng commented
还是希望支持一下这个事情

2019-04-01 02:23 UTC, jiang443 commented
我们又不违法，又不反动，不可能被封。现在是法治社会了。我们只是要求合法的权利。
还有，请不要看不起农民。你的前两代很可能就是农民。

2019-04-01 02:25 UTC, fullwinsjuice commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

很多人骂你是对的，因为nmsl

2019-04-01 02:25 UTC, MachiBarton commented
@pjjr123 看您的项目空空如也，怕不是水军吧。你也配称程序员，你吃的饭难道不是农民辛苦劳动得来？你优质的生活难道不是当年以工农为主体的解放军披肝沥胆创立的？你也配叫人？牲口，活蛆，工贼。

2019-04-01 02:26 UTC, athinboy commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀


劣性繁殖 ？ 你才是繁殖出来的。请离开github！
大家举报他吧，让github清除他。

2019-04-01 02:29 UTC, marsprince commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

兄弟你最好换个说法，比如农民阶级局限性

2019-04-01 02:29 UTC, MachiBarton commented
> > 很多人骂我 但是你们想一下
> > 我说的是不是事实
> > 社会资源总量不变
> > 低端人口大量劣性繁殖
> > 最后就是生存环境恶化
> > 你们搞的什么996.icu
> > 最后的结果
> > 就是Github被长城防火墙封杀
> 
> 劣性繁殖 ？ 你才是繁殖出来的。请离开github！
> 大家举报他吧，让github清除他。

他才进github 三天。这就不用我多说了吧，资本家开始动手了

2019-04-01 02:30 UTC, Jason2048 commented
> > > * README 里面放列表不太合适，放列表的链接更好
> > > * 已有几个类似的PR ref https://github.com/996icu/996.ICU/pulls?utf8=%E2%9C%93&q=supporting
> > > * repo主创者应该有一些自己的考虑和计划，且稍安勿躁，不必提重复的PR.
> > 
> > 
> > 主要原因是考虑到现在license还是草案阶段，可能存在法律风险。再完善一些后，会加入一个项目列表的。
> 
> 我个人觉得可以先用起来？毕竟现在的任务是要让更多的人知道支持这件事，draft可能有些没考虑到不够全面，或者可以钻空子的地方，但是基本上问题不大。MIT或者UIUC/NCSA之类的license也基本上就是简短的两三段，里面肯定也有不够全面的地方，如果真的要写一个完全没有漏洞的协议，这个时间可能是一两年。

>是的，可以先搞起来。

2019-04-01 02:31 UTC, DukeGJ commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

套用大德鲁伊的话来说：我最大的错误，就是让你这种人吃的太饱了

2019-04-01 02:36 UTC, asuradagsx1 commented
> > 中国程序员
> > 基本都是些农民大学生
> > 人多的跟蟑螂一样
> > 你不做后面几万个人排队
> > 最后的结果 就是996 007
> > 农民的原罪
> > 也是中国问题的原罪
> > 就是农民太多
> > 而且劣性繁殖
> 
> 兄弟你最好换个说法，比如农民阶级局限性

照他这说法，就消灭一半，你怎么界定这个人算不算精英呢？灭霸方法是无差别伤害，那跟你宣传的精英社会不是背道而驰么。再说了，社会全部精英阶层，发展到后面，肯定也会出现精英阶层的高中低差异，到头来不是一样的嘛。就算不停消灭低阶层，那原先的中层不就也变成了低层嘛？循环往复……这逻辑思维，当个程序员真难为了~

2019-04-01 02:38 UTC, BestiOSDev commented
这就是一个项目 别扯到阶级和政治




| |
董招兵
|
|
邮箱：dzb8818082@163.com
|

签名由 网易邮箱大师 定制

在2019年04月01日 10:37，asuradagsx1 写道：

中国程序员
基本都是些农民大学生
人多的跟蟑螂一样
你不做后面几万个人排队
最后的结果 就是996 007
农民的原罪
也是中国问题的原罪
就是农民太多
而且劣性繁殖

兄弟你最好换个说法，比如农民阶级局限性

照他这说法，就消灭一半，你怎么界定这个人算不算精英呢？灭霸方法是无差别伤害，那跟你宣传的精英社会不是背道而驰么。再说了，社会全部精英阶层，发展到后面，肯定也会出现精英阶层的高中低差异，到头来不是一样的嘛。就算不停消灭低阶层，那原先的中层不就也变成了低层嘛？循环往复……这逻辑思维，当个程序员真难为了~

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-04-01 02:42 UTC, freemanpeng commented
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪

你说的是对的
但是说话也是一门艺术
如果你能说的稍微委婉一些
或许很多人就能欣然接受

2019-04-01 02:44 UTC, freemanpeng commented
> > > 很多人骂我 但是你们想一下
> > > 我说的是不是事实
> > > 社会资源总量不变
> > > 低端人口大量劣性繁殖
> > > 最后就是生存环境恶化
> > > 你们搞的什么996.icu
> > > 最后的结果
> > > 就是Github被长城防火墙封杀
> > 
> > 
> > 劣性繁殖 ？ 你才是繁殖出来的。请离开github！
> > 大家举报他吧，让github清除他。
> 
> 他才进github 三天。这就不用我多说了吧，资本家开始动手了

他话虽然说的不好听
但是也是无法改变的事实
不是吗

2019-04-01 02:46 UTC, zsukai commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

你能去死吗

2019-04-01 02:49 UTC, zsukai commented
> > 很多人骂我 但是你们想一下
> > 我说的是不是事实
> > 社会资源总量不变
> > 低端人口大量劣性繁殖
> > 最后就是生存环境恶化
> > 你们搞的什么996.icu
> > 最后的结果
> > 就是Github被长城防火墙封杀
> 
> 有道理，但别歧视农民哦，这只是阶级的局限性而已
一点道理都没有，真是大言不惭。多读几本书去吧

2019-04-01 02:50 UTC, iambiglee commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

老哥,github水军不好混..这里不是微博.有无知的人给你带节奏.呵呵

2019-04-01 03:13 UTC, javacodecreeks commented
每家公司都存在拍马屁打小报告的人，我遇到不少这样的同事，这些人确实很恶心，平时跟你都是称兄道弟的。不过很赞赏哥们你的这种勇气啊！@BestiOSDev

2019-04-01 03:16 UTC, BestiOSDev commented
我也是长期996 主要是想着工作不干满一年 对以后找工作有影响 所以才干满一年就辞职了。




| |
董招兵
|
|
邮箱：dzb8818082@163.com
|

签名由 网易邮箱大师 定制

在2019年04月01日 11:14，javacodecreeks 写道：

每家公司都存在拍马屁打小报告的人，我遇到不少这样的同事，这些人确实很恶心，平时跟你都是称兄道弟的。不过很赞赏哥们你的这种勇气啊！@BestiOSDev

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-04-01 03:17 UTC, jimwong666 commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀



> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

真是个睿智！！！！！

2019-04-01 03:34 UTC, junn1996 commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

你是因为出身农民过于自卑才说这种话吗？ 说劣性繁殖前先想想自己，把自己的屌剁了先

2019-04-01 04:02 UTC, wangzhiok commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

呵呵，可以试下封github的后果，封了后长城防火墙就会直接垮掉，很多源码都是直接采用github的代码

2019-04-01 04:14 UTC, CantoneseTeaAndMilk commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

说吧，拿了美国人多少钱，值得你这么黑中国。

2019-04-01 04:15 UTC, CantoneseTeaAndMilk commented
> > 很多人骂我 但是你们想一下
> > 我说的是不是事实
> > 社会资源总量不变
> > 低端人口大量劣性繁殖
> > 最后就是生存环境恶化
> > 你们搞的什么996.icu
> > 最后的结果
> > 就是Github被长城防火墙封杀
> 
> 呵呵，可以试下封github的后果，封了后长城防火墙就会直接垮掉，很多源码都是直接采用github的代码


> > 很多人骂我 但是你们想一下
> > 我说的是不是事实
> > 社会资源总量不变
> > 低端人口大量劣性繁殖
> > 最后就是生存环境恶化
> > 你们搞的什么996.icu
> > 最后的结果
> > 就是Github被长城防火墙封杀
> 
> 呵呵，可以试下封github的后果，封了后长城防火墙就会直接垮掉，很多源码都是直接采用github的代码

你这条帖子值1$。拿好，滚。

2019-04-01 04:37 UTC, xiuyoung89 commented
mark
一是想跟 @pjjr123说句，别在这里秀你智商的上限，fuck off！

2019-04-01 04:42 UTC, ShuaiShuaiLee commented
优客服率先采用996.ICUl License开源协议
http://software.it168.com/a2019/0401/5179/000005179212.shtml

2019-04-01 04:42 UTC, hq2999 commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

你祖上不也是“蟑螂一样”“低端人口大量劣性繁殖”的幸存者之一吗？

2019-04-01 04:57 UTC, yyrdl commented
对那些 不当言论，大家点一个鄙视的emoji 就好，不回复他，不要给他存在感

2019-04-01 05:09 UTC, yyrdl commented
已经在自己一个还未完工的[项目](https://github.com/yyrdl/x-search)里面加了 996ICU License了 ,
MIT & 996ICU License 这种声明方法对不对？

2019-04-01 05:20 UTC, kattgu7 commented
Hi, I have got both the English version and Chinese Version of the license done. Pls check my repo! I will ask them to merge the Chinese version this afternoon. Thanks!

中文版的anti-996和英文版的anti-996许可证都已经做好了！暂时还没有让官方merge，但是需要用的人可以从我的repo里面直接拿中文版使用！谢谢！

2019-04-01 05:21 UTC, mitolH commented
https://krcom.cn/2334162530/episodes/2358773:4356003609685723

【#小伙骑车逆行被拦后爆发# 称压力好大】杭州文一路文菁路口附近，傅警官正带队整治电动车的交通违法行为，一位小伙骑单车逆行而来，交警把他拦下后，小伙接到一个电话，没想到打完电话，小伙子摔了手机，彻底崩溃了。

2019-04-01 05:22 UTC, BestiOSDev commented
总有傻屌在这里拉仇恨 显示自己的优越感




| |
董招兵
|
|
邮箱：dzb8818082@163.com
|

签名由 网易邮箱大师 定制

在2019年04月01日 12:58，Jason 写道：

对那些 不当言论，大家点一个鄙视的emoji 就好，不回复他，不要给他存在感

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-04-01 05:59 UTC, zhaojianxinTest commented
那个人说得对，只是说得太直接了，一个996扯到阶级政治确实不合适，就这么说，北京部分GDP都是培训机构撑起来的，4个月月薪过万，720行，行行转it，任何行业都扛不住，现在中小公司统招名校一本/二本起步+3年经验，说白了，人太多了，996你不去，过段时间007 最高10k真的会踢破门槛，有些创造的泡沫还需一些人去解决和消化，做吃技术的高级人才吧，这个快餐时代别无办法。。。。。你看刚进公司0经验的骗子不干活工资还是你1.5倍。。。

2019-04-01 06:33 UTC, flame9012 commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

对对对，农民不该写代码，码农这种高端工作就该让你这种社会精英来做，农民这种低端人口还是乖乖世世代代种田去吧

2019-04-01 06:37 UTC, flame9012 commented
> > 中国程序员
> > 基本都是些农民大学生
> > 人多的跟蟑螂一样
> > 你不做后面几万个人排队
> > 最后的结果 就是996 007
> > 农民的原罪
> > 也是中国问题的原罪
> > 就是农民太多
> > 而且劣性繁殖
> 
> 你祖上不也是“蟑螂一样”“低端人口大量劣性繁殖”的幸存者之一吗？

刚写了骂他的又删了，突然觉得你跟一个智障费啥劲呢，只不过就是隐藏在网络背后的一个无知的傻子而已

2019-04-01 06:53 UTC, libbGit commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

放屁，权利是靠自己维护来的。不是当下存在的，就是合理的。再说劳动法明确有规定。你只是一个希望996，然后靠他们的业绩，拿到奖金的鼠目寸光的鼠辈而已。我们希望的不是仅仅是双休，能够有更多的时间陪陪家人，有更好的睡眠，用更好的状态迎接明天的工作而已。这也有错？？？如果这也有错。我他妈就不该活在这样充满“人血馒头“社会

2019-04-01 06:56 UTC, qwertyuiop6 commented
资本从来到世间，头到脚每个毛孔都滴着血和肮脏的东西 --马克思

2019-04-01 06:58 UTC, lvao813 commented
> > > 中国程序员
> > > 基本都是些农民大学生
> > > 人多的跟蟑螂一样
> > > 你不做后面几万个人排队
> > > 最后的结果 就是996 007
> > > 农民的原罪
> > > 也是中国问题的原罪
> > > 就是农民太多
> > > 而且劣性繁殖
> > 
> > 
> > 你祖上不也是“蟑螂一样”“低端人口大量劣性繁殖”的幸存者之一吗？
> 
> 刚写了骂他的又删了，突然觉得你跟一个智障费啥劲呢，只不过就是隐藏在网络背后的一个无知的傻子而已

毕竟有网线守护神，这种言论纯粹是来挑事的

2019-04-01 07:06 UTC, baijiu1 commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

权利是自己争取来的，而不是通过某些灭绝理论来减少人口数量达到目的，这已经是本末倒置了。农民有什么罪？谁家祖上不是农民？说道劣性，难道这种发言就不是劣性了吗？

2019-04-01 07:20 UTC, Lzp950504 commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

瞧不起农民？瞧不起底层？没有农民养着你，你吃粪？狗嘴里吐不出象牙。

2019-04-01 07:30 UTC, bugithubUser commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

资本剥削者走狗你来辣

2019-04-01 07:33 UTC, qiaoshanGH commented
> > > > 很多人骂我 但是你们想一下
> > > > 我说的是不是事实
> > > > 社会资源总量不变
> > > > 低端人口大量劣性繁殖
> > > > 最后就是生存环境恶化
> > > > 你们搞的什么996.icu
> > > > 最后的结果
> > > > 就是Github被长城防火墙封杀
> > > 
> > > 
> > > 劣性繁殖 ？ 你才是繁殖出来的。请离开github！
> > > 大家举报他吧，让github清除他。
> > 
> > 
> > 他才进github 三天。这就不用我多说了吧，资本家开始动手了
> 
> 他话虽然说的不好听
> 但是也是无法改变的事实
> 不是吗

你意思他说的对咯？哪里对了？那为何不想想这种局面的根本原因呢？
如果人人遵纪守法，如果企业都遵纪守法，如果。。。。。。
会有这么多你眼中的“农民”？
说到底，请尊重法律

2019-04-01 07:45 UTC, mqliutie commented
@CN-YUANYU  表格现在维护在哪里了呀 想看看呢

2019-04-01 07:58 UTC, fengxiao361 commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

所以你是个什么种？

2019-04-01 08:37 UTC, zhongxigong commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

你是被繁殖出来的千古奇葩。你可以去死了。人人生而平等，决定一个人的是环境，很多你眼中所谓的低端人口如果从出生就在北上广，他们大多数人活得都不会比你差。请不要觉得自己多么牛逼，只是你在的环境比他们好一点。你看不起谁？你觉得你是自己牛逼？

2019-04-01 08:42 UTC, zhongxigong commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖


> > 很多人骂我 但是你们想一下
> > 我说的是不是事实
> > 社会资源总量不变
> > 低端人口大量劣性繁殖
> > 最后就是生存环境恶化
> > 你们搞的什么996.icu
> > 最后的结果
> > 就是Github被长城防火墙封杀
> 
> 你是被繁殖出来的千古奇葩。你可以去死了。人人生而平等，决定一个人的是环境，很多你眼中所谓的低端人口如果从出生就在北上广，他们大多数人活得都不会比你差。请不要觉得自己多么牛逼，只是你在的环境比他们好一点。你看不起谁？你觉得你是自己牛逼？

另外请你闭嘴。

2019-04-01 08:43 UTC, lzyyzlwsldx commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

真是个秀儿

2019-04-01 08:50 UTC, joe-lwc commented
顶起来，维护我们的合法权益！！！

2019-04-01 08:53 UTC, CheukFaiho commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

回答：你说的不是事实。

1. 你搞错了逻辑关系。按照你的想法，这是一个无解的恶性循环。但实际上，解决「农民的原罪」问题，唯一的也是根本的途径，就是大规模普及高等教育，改变传统的生育观，从整体层面提高人口素质，把法制、争取个人合法权益的观念普及到每一个普通人的心中。

在这个层面上，新中国的扫盲教育以及高等教育可以说是全世界做的最好的，没有之一。

2. 你的观点相当狭隘，而且都是建立在一个错误的「社会资源总量不变」的前提下的。但是，2019 年的生产力和生产总值会和 2009 年的一样吗？我国当前的目标是「把蛋糕做大」以及不断优化调整分配制度，而不是「消灭无用的低端人口」。

3. 高等教育普及后带来的必然负面结果，确实是社会竞争加剧。但这并不代表，牺牲自己的合法利益、损害自己的身体健康去换取金钱就是值得提倡的、合法的。合理的竞争可以促进人口整体素质提高，但现在的 996 显然是不合理的，不仅让劳动者消极怠工，还会进一步丧失完善自我的时间和空间。

4. 你单纯将这个问题的罪责归给了农民，完全是无法立足的。人口问题的解决时间是以 50 年甚至 100 年来计算的，权益的争取也是要流血的，这点学过历史的人都明白。你只看到了短浅的一小部分，却不能看到整体的社会现状和历史进程。

5. 我们这里反对的并非是「自愿」或者是「创业必须」的 996，而是反对违法的、非自愿的甚至是强迫的，且没有发放任何补偿的 996。

6. 法律所赋予你的权利，你选择不使用，那是你的选择。但是，你没有任何权利去辱骂、藐视那些拿起法律武器保护自己合法权利的人。

以上，不服欢迎来辩。

来自一个文科生，目前是互联网公司运营。

2019-04-01 09:11 UTC, 996icu commented
> > > * README 里面放列表不太合适，放列表的链接更好
> > > * 已有几个类似的PR ref https://github.com/996icu/996.ICU/pulls?utf8=%E2%9C%93&q=supporting
> > > * repo主创者应该有一些自己的考虑和计划，且稍安勿躁，不必提重复的PR.
> > 
> > 
> > 主要原因是考虑到现在license还是草案阶段，可能存在法律风险。再完善一些后，会加入一个项目列表的。
> 
> 我个人觉得可以先用起来？毕竟现在的任务是要让更多的人知道支持这件事，draft可能有些没考虑到不够全面，或者可以钻空子的地方，但是基本上问题不大。MIT或者UIUC/NCSA之类的license也基本上就是简短的两三段，里面肯定也有不够全面的地方，如果真的要写一个完全没有漏洞的协议，这个时间可能是一两年。

已更新入README中，格式相比此PR有些变化，大家随时提建议，非常感谢。

2019-04-01 09:19 UTC, seanshaojie commented
> 很多人骂我 但是你们想一下
> 我说的是不是事实
> 社会资源总量不变
> 低端人口大量劣性繁殖
> 最后就是生存环境恶化
> 
> 你们搞的什么996.icu
> 最后的结果
> 就是Github被长城防火墙封杀

有些东西不做永远不知道结果，想你这种永远只知道怨天尤人的，不是反派就是在成为反派的路上。

2019-04-01 09:21 UTC, lzm420241 commented
> 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996

这种事情我也碰到过，说完第二天有个人就去打报告，然后各级领导找我谈话，最后人事让我签个离职，我没啥啥就走了。其实我觉得这种事情也不用跟别人说，那些想996的你找他聊反而让那些还在决定的人由于看到你的离职导致他们觉得996是应该的。所以我现在找了一个965的工作，人也轻松了很多了😄，但愿国人都不要996把，即使自己想，也不要打别人的报告！

2019-04-01 09:27 UTC, BigBrother5 commented
> 中国程序员
> 基本都是些农民大学生
> 人多的跟蟑螂一样
> 你不做后面几万个人排队
> 最后的结果 就是996 007
> 农民的原罪
> 也是中国问题的原罪
> 就是农民太多
> 而且劣性繁殖

注册个小号来喷？笑死

2019-04-01 09:31 UTC, 0lovesakura0 commented
人性无贵贱

2019-04-01 09:56 UTC, razerdp commented
[**BasePopup**](https://github.com/razerdp/BasePopup)参上~

已加入996LICENSE全家桶

2019-04-01 10:07 UTC, JagdtigerI commented
珍爱生命,远离996,生而为人,不做机器

2019-04-01 10:16 UTC, qwas982 commented
> 那个人说得对，只是说得太直接了，一个996扯到阶级政治确实不合适，就这么说，北京部分GDP都是培训机构撑起来的，4个月月薪过万，720行，行行转it，任何行业都扛不住，现在中小公司统招名校一本/二本起步+3年经验，说白了，人太多了，996你不去，过段时间007 最高10k真的会踢破门槛，有些创造的泡沫还需一些人去解决和消化，做吃技术的高级人才吧，这个快餐时代别无办法。。。。。你看刚进公司0经验的骗子不干活工资还是你1.5倍。。。

要把蛋糕做大呀,需要行业的共同努力,我的方法是搞中文汉字汉语编程.现在行业的需求缺口只有那么大,那自然是"人太多",因为没有人去创造新的需求消化新的需求和产品.试想下,如果更多人知道怎么编程,那么也就有更多的脑子思考怎么盘活产业链.那么也就有更多的就业机会,蛋糕也就随之被做大了,结果就是共赢,所有人都可以生存拿高薪.中文汉字汉语编程我在研究,目的就是为了让更多人轻易学会编程.顺带提升国人的认知和素质,和咱们国产业质量和创新力.  
有这个想法的话可以详聊,咱共同努力改变当前中国社会!
我的研究已经进展到比较关键的时候了,一人的力量太小.

2019-04-01 10:23 UTC, qwas982 commented
> > 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996
> 
> 同意。自己的权利要自己去争取，而不是妥协**卑微地** 迁就，**懦弱地**退缩。正式那些为了为己在老板面前装好人的奸邪小人的迁就那些老板，造成了加班制度陷入了一个恶性循环：你不加班，你滚，有的是劳动力。同时，一个公司实行加班制度，其他公司也会效仿。
> 
> 说白了还是廉价劳动力供远大于求

要把蛋糕做大呀,需要行业的共同努力,我的方法是搞中文汉字汉语编程.现在行业的需求缺口只有那么大,那自然是"人太多",因为没有人去创造新的需求消化新的需求和产品.试想下,如果更多人知道怎么编程,那么也就有更多的脑子思考怎么盘活产业链.那么也就有更多的就业机会,蛋糕也就随之被做大了,结果就是共赢,所有人都可以生存拿高薪.中文汉字汉语编程我在研究,目的就是为了让更多人轻易学会编程.顺带提升国人的认知和素质,和咱们国产业质量和创新力.
有这个想法的话可以详聊,咱共同努力改变当前中国社会!
我的研究已经进展到比较关键的时候了,一人的力量太小.

2019-04-01 10:31 UTC, uyaddayu commented
> > > 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996
> > 
> > 
> > 同意。自己的权利要自己去争取，而不是妥协**卑微地** 迁就，**懦弱地**退缩。正式那些为了为己在老板面前装好人的奸邪小人的迁就那些老板，造成了加班制度陷入了一个恶性循环：你不加班，你滚，有的是劳动力。同时，一个公司实行加班制度，其他公司也会效仿。
> > 说白了还是廉价劳动力供远大于求
> 
> 要把蛋糕做大呀,需要行业的共同努力,我的方法是搞中文汉字汉语编程.现在行业的需求缺口只有那么大,那自然是"人太多",因为没有人去创造新的需求消化新的需求和产品.试想下,如果更多人知道怎么编程,那么也就有更多的脑子思考怎么盘活产业链.那么也就有更多的就业机会,蛋糕也就随之被做大了,结果就是共赢,所有人都可以生存拿高薪.中文汉字汉语编程我在研究,目的就是为了让更多人轻易学会编程.顺带提升国人的认知和素质,和咱们国产业质量和创新力.
> 有这个想法的话可以详聊,咱共同努力改变当前中国社会!
> 我的研究已经进展到比较关键的时候了,一人的力量太小.

易语言呢？

2019-04-01 10:40 UTC, iiCircle commented
有没有QQ或者微信交流群 ？

2019-04-01 10:40 UTC, iiCircle commented
有没有QQ或者微信交流群 ？

2019-04-01 10:40 UTC, iiCircle commented
有没有QQ或者微信交流群 ？

2019-04-01 10:41 UTC, qwas982 commented
> > > > 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996
> > > 
> > > 
> > > 同意。自己的权利要自己去争取，而不是妥协**卑微地** 迁就，**懦弱地**退缩。正式那些为了为己在老板面前装好人的奸邪小人的迁就那些老板，造成了加班制度陷入了一个恶性循环：你不加班，你滚，有的是劳动力。同时，一个公司实行加班制度，其他公司也会效仿。
> > > 说白了还是廉价劳动力供远大于求
> > 
> > 
> > 要把蛋糕做大呀,需要行业的共同努力,我的方法是搞中文汉字汉语编程.现在行业的需求缺口只有那么大,那自然是"人太多",因为没有人去创造新的需求消化新的需求和产品.试想下,如果更多人知道怎么编程,那么也就有更多的脑子思考怎么盘活产业链.那么也就有更多的就业机会,蛋糕也就随之被做大了,结果就是共赢,所有人都可以生存拿高薪.中文汉字汉语编程我在研究,目的就是为了让更多人轻易学会编程.顺带提升国人的认知和素质,和咱们国产业质量和创新力.
> > 有这个想法的话可以详聊,咱共同努力改变当前中国社会!
> > 我的研究已经进展到比较关键的时候了,一人的力量太小.
> 
> 易语言呢？

我研究过,易语言1不开源自由,2不是从最底层进行改变.
我现在研究到汇编器这一层.中文汉字汉语编程需要建立新的生态.必须得从最底层做起.
软件编程可改变的最低抽象就是机器码指令到助记符指令的一一对应的对应关系,再往下就是硬件的事了,那我们是做不了的,起码短期是做不了.
我们有人多力量大的优势,可以凭借此实现弯道超车.因为我们如果再造一个产业链,还能永远挣脱掉西方人的卡脖子.

2019-04-01 10:53 UTC, uyaddayu commented
> > > > > 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996
> > > > 
> > > > 
> > > > 同意。自己的权利要自己去争取，而不是妥协**卑微地** 迁就，**懦弱地**退缩。正式那些为了为己在老板面前装好人的奸邪小人的迁就那些老板，造成了加班制度陷入了一个恶性循环：你不加班，你滚，有的是劳动力。同时，一个公司实行加班制度，其他公司也会效仿。
> > > > 说白了还是廉价劳动力供远大于求
> > > 
> > > 
> > > 要把蛋糕做大呀,需要行业的共同努力,我的方法是搞中文汉字汉语编程.现在行业的需求缺口只有那么大,那自然是"人太多",因为没有人去创造新的需求消化新的需求和产品.试想下,如果更多人知道怎么编程,那么也就有更多的脑子思考怎么盘活产业链.那么也就有更多的就业机会,蛋糕也就随之被做大了,结果就是共赢,所有人都可以生存拿高薪.中文汉字汉语编程我在研究,目的就是为了让更多人轻易学会编程.顺带提升国人的认知和素质,和咱们国产业质量和创新力.
> > > 有这个想法的话可以详聊,咱共同努力改变当前中国社会!
> > > 我的研究已经进展到比较关键的时候了,一人的力量太小.
> > 
> > 
> > 易语言呢？
> 
> 我研究过,易语言1不开源自由,2不是从最底层进行改变.
> 我现在研究到汇编器这一层.中文汉字汉语编程需要建立新的生态.必须得从最底层做起.
> 软件编程可改变的最低抽象就是机器码指令到助记符指令的一一对应的对应关系,再往下就是硬件的事了,那我们是做不了的,起码短期是做不了.
> 我们有人多力量大的优势,可以凭借此实现弯道超车.因为我们如果再造一个产业链,还能永远挣脱掉西方人的卡脖子.
> 自己有才是真的有,首先得自己有.这不是闭门造车闭关锁国,西方人想与我们交流也可以来学我们的语言,正如我们当前要使用这种工具得去学TA们的语言一样.

汇编好像都是英文的（您加油吧，写一套中文的汇编出来再说

2019-04-01 11:26 UTC, king41409 commented
> > 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996
> 
> 同意。自己的权利要自己去争取，而不是妥协**卑微地** 迁就，**懦弱地**退缩。正式那些为了为己在老板面前装好人的奸邪小人的迁就那些老板，造成了加班制度陷入了一个恶性循环：你不加班，你滚，有的是劳动力。同时，一个公司实行加班制度，其他公司也会效仿。
> 
> 说白了还是廉价劳动力供远大于求

国家的二胎政策正在提供新的廉价劳动力。

2019-04-01 11:30 UTC, qwas982 commented
> > > > > > 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996
> > > > > 
> > > > > 
> > > > > 同意。自己的权利要自己去争取，而不是妥协**卑微地** 迁就，**懦弱地**退缩。正式那些为了为己在老板面前装好人的奸邪小人的迁就那些老板，造成了加班制度陷入了一个恶性循环：你不加班，你滚，有的是劳动力。同时，一个公司实行加班制度，其他公司也会效仿。
> > > > > 说白了还是廉价劳动力供远大于求
> > > > 
> > > > 
> > > > 要把蛋糕做大呀,需要行业的共同努力,我的方法是搞中文汉字汉语编程.现在行业的需求缺口只有那么大,那自然是"人太多",因为没有人去创造新的需求消化新的需求和产品.试想下,如果更多人知道怎么编程,那么也就有更多的脑子思考怎么盘活产业链.那么也就有更多的就业机会,蛋糕也就随之被做大了,结果就是共赢,所有人都可以生存拿高薪.中文汉字汉语编程我在研究,目的就是为了让更多人轻易学会编程.顺带提升国人的认知和素质,和咱们国产业质量和创新力.
> > > > 有这个想法的话可以详聊,咱共同努力改变当前中国社会!
> > > > 我的研究已经进展到比较关键的时候了,一人的力量太小.
> > > 
> > > 
> > > 易语言呢？
> > 
> > 
> > 我研究过,易语言1不开源自由,2不是从最底层进行改变.
> > 我现在研究到汇编器这一层.中文汉字汉语编程需要建立新的生态.必须得从最底层做起.
> > 软件编程可改变的最低抽象就是机器码指令到助记符指令的一一对应的对应关系,再往下就是硬件的事了,那我们是做不了的,起码短期是做不了.
> > 我们有人多力量大的优势,可以凭借此实现弯道超车.因为我们如果再造一个产业链,还能永远挣脱掉西方人的卡脖子.
> > 自己有才是真的有,首先得自己有.这不是闭门造车闭关锁国,西方人想与我们交流也可以来学我们的语言,正如我们当前要使用这种工具得去学TA们的语言一样.
> 
> 汇编好像都是英文的（您加油吧，写一套中文的汇编出来再说

我说的是汇编器,不是说汇编.汇编不一定非得英文,(我说了,一个人力量太小,需要组队一起搞才行,所以说对此感兴趣愿意一起搞的详聊

2019-04-01 12:05 UTC, KnifeOfLife commented
996icu的github地址已经被微信屏蔽了，理由是包含违法及违规内容，不清楚到底哪里违法违规了。本项目的目的是维护劳动法、保护劳动者的合法权益，是国家法律法规的坚定守护者。腾讯的行为与人民意愿及法律法规背道而驰，我非常怀疑腾讯的立场与背景。

2019-04-01 14:04 UTC, zerowangyu commented
我感觉不光是996  还有那些大小周  加班不给补偿只让调休的，都应该曝光。感觉国内互联网公司和国外最大的差距在于，我们是996 是大小周、并且不去争取我们的权益，而他们会。

2019-04-01 14:23 UTC, l585826 commented
996icu的github地址已经被360浏览器屏蔽了。。。

2019-04-01 15:11 UTC, yijvyan commented
996的github地址在360安全浏览器上已经被屏蔽了，网页上的标题是存在违法信息的网站，弹出框是：您当前访问的网站存在违法信息，请您关闭页面。还禁止切换ie内核！现在腾讯，360这些大公司，已经害怕了，支持这个项目！顶起来！

2019-04-01 15:46 UTC, CN-YUANYU commented
996icu的github地址已经被   QQ   屏蔽了 理由是包含违法及违规内容，不清楚到底哪里违法违规了。本项目的目的是维护劳动法、保护劳动者的合法权益，是国家法律法规的坚定守护者。腾讯的行为与人民意愿及法律法规背道而驰，我非常怀疑腾讯的立场与背景。

2019-04-02 00:00 UTC, zhangxundi commented
能否创建一个屏蔽了996icu，以及因为员工参与996icu讨论而被辞退的公司黑名单？

发自我的 iPhone

在 2019年4月1日，23:47，yuany <notifications@github.com<mailto:notifications@github.com>> 写道：


996icu的github地址已经被 QQ 屏蔽了 理由是包含违法及违规内容，不清楚到底哪里违法违规了。本项目的目的是维护劳动法、保护劳动者的合法权益，是国家法律法规的坚定守护者。腾讯的行为与人民意愿及法律法规背道而驰，我非常怀疑腾讯的立场与背景。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/996icu/996.ICU/pull/24788#issuecomment-478634060>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AlvxKTw3viguV0f6rZciJVoIj31o0EW4ks5vcioDgaJpZM4cUSHq>.

2019-04-02 00:15 UTC, hui305 commented
建议名字改一下！初看，还以为支持996呢。建议改成 反996license

2019-04-02 00:29 UTC, hui305 commented
建议建立电报群，把大家组织起来！

2019-04-02 00:50 UTC, bugithubUser commented
> 996的github地址在360安全浏览器上已经被屏蔽了，网页上的标题是存在违法信息的网站，弹出框是：您当前访问的网站存在违法信息，请您关闭页面。还禁止切换ie内核！现在腾讯，360这些大公司，已经害怕了，支持这个项目！顶起来！

![image](https://user-images.githubusercontent.com/43409097/55368321-ea062b80-5523-11e9-9bcf-78ce22783793.png)按照劳动法保护权益被说成是违法信息，贼喊捉贼还行（360极速浏览器）；通过TIM打开的996icu会弹出一个title为“管家拦截页面”的空白页。

2019-04-02 01:02 UTC, UniqueSimon commented
> 996的github地址在360安全浏览器上已经被屏蔽了，网页上的标题是存在违法信息的网站，弹出框是：您当前访问的网站存在违法信息，请您关闭页面。还禁止切换ie内核！现在腾讯，360这些大公司，已经害怕了，支持这个项目！顶起来！

牛皮，自己996违法还说别人违法，360当自己家是法院还是人大啊

2019-04-02 01:16 UTC, zszen commented
不光是IT届，能否把国内各行业的工作畜处唤醒，需要这样一个埂醒之钟

2019-04-02 01:20 UTC, EarthTeenager commented
国内其他行业的人很少上GIT吧

2019-04-02 01:23 UTC, hui305 commented
楼上，不是靠嘴巴吹的！踏踏实实做些能落实的小事吧！这场斗争在国内是很艰巨的！
我们要谨慎对待！要有计划和策略！

2019-04-02 01:29 UTC, namewhat commented
尼玛的，看到那么多大公司屏蔽了这个项目，阶级斗争的感觉立马鲜明了起来。

2019-04-02 01:29 UTC, yyrdl commented
> > 996的github地址在360安全浏览器上已经被屏蔽了，网页上的标题是存在违法信息的网站，弹出框是：您当前访问的网站存在违法信息，请您关闭页面。还禁止切换ie内核！现在腾讯，360这些大公司，已经害怕了，支持这个项目！顶起来！
> 
> 牛皮，自己996违法还说别人违法，360当自己家是法院还是人大啊

哈哈哈， 是否可以组团去微博@ 周鸿伟 跟 马化腾

2019-04-02 01:37 UTC, xxllp commented
期待更多优秀项目加入，目前没啥特别牛的项目

2019-04-02 01:39 UTC, hui305 commented
大家最好不要把这个引向政治方向，这很危险！（什么阶级斗争什么的）
当我们力量小的时候，先不要和大公司对抗，慢慢发展！
在广大的国内程序员中达成共识！这个才是最重要的！
电报群：
https://t.me/anti996

2019-04-02 01:41 UTC, xutongbao commented
其实有些公司加班也是程序员不团结导致的，有些程序员还故意加班，表现的很积极，其他程序员如果不加班就会被显现出来！

2019-04-02 01:44 UTC, namewhat commented
> 大家最好不要把这个引向政治方向，这很危险！（什么阶级斗争什么的）
> 当我们力量小的时候，先不要和大公司对抗，慢慢发展！
> 在广大的国内程序员中达成共识！这个才是最重要的！
> 电报群：
> https://t.me/anti996



> 大家最好不要把这个引向政治方向，这很危险！（什么阶级斗争什么的）
> 当我们力量小的时候，先不要和大公司对抗，慢慢发展！
> 在广大的国内程序员中达成共识！这个才是最重要的！
> 电报群：
> https://t.me/anti996

不好意思，是我失言了。

2019-04-02 01:48 UTC, hui305 commented
在国内争取合法的权益是非常难的！但这是很好的一步！
不管成功与否，起码这次运动在国内程序员中算是一种启蒙！将载入史册！
希望大家以一种严肃的态度对待！这不是闹着玩的！

2019-04-02 01:52 UTC, GreekPanda commented
哥一直说有些公司996纯粹就是管理层的无能表现，整体来说现在的公司经营都比较艰难，尤其是创业公司，为了追赶进度，有时候真的要加班很晚（不好意思，鄙人就是开了小公司），但这不是常态，是项目紧张的时候才用非常之策，剩下的工作时间就是正常的上班时间。

码农本来就是剧耗费脑力的活儿，一天能要能高度集中注意力4小时，出的东西有质量保证，已经非常了不起。一天连续工作十几个小时，谁特么信弄出来的东西质量咋样？所以要么就是在磨洋工，要么就是干了一堆烂事。做管理最重要控制好节奏，张弛有序，劳逸结合。

不过大部分公司管理都是混的居多，不求有功，但求无过，反正公司不是自己的，这是天朝千年政治生态，无药可救

2019-04-02 02:02 UTC, zxkjack123 commented
> 哥一直说有些公司996纯粹就是管理层的无能表现，整体来说现在的公司经营都比较艰难，尤其是创业公司，为了追赶进度，有时候真的要加班很晚（不好意思，鄙人就是开了小公司），但这不是常态，是项目紧张的时候才用非常之策，剩下的工作时间就是正常的上班时间。
> gai bian
> 码农本来就是剧耗费脑力的活儿，一天能要能高度集中注意力4小时，出的东西有质量保证，已经非常了不起。一天连续工作十几个小时，谁特么信弄出来的东西质量咋样？所以要么就是在磨洋工，要么就是干了一堆烂事。做管理最重要控制好节奏，张弛有序，劳逸结合。
> 
> 不过大部分公司管理都是混的居多，不求有功，但求无过，反正公司不是自己的，这是天朝千年政治生态，无药可救

不是无药可救，只不过要改变这种状态，需要有人付出努力，需要很长时间，愿意这样做的个人很少。但是当我们形成一个集体，就可以有前赴后继的人来为改变996而努力，一点一点慢慢改变。
这是一个很好的开端，继续做下去，肯定不什么都不做要好。

2019-04-02 02:20 UTC, stoneAlbert commented
你们爱加班吗? 我只接受一周两次内共两小时内的加班 坚决抵制周末加班 谁爱加谁加 不行就换 我90后尚且如此 未来95后00后更如此 各位996领导 告辞

2019-04-02 02:22 UTC, xxllp commented
996 不灭天理难容

2019-04-02 02:45 UTC, zxkjack123 commented
大家理智一点，不要一开始就认定996的公司做错了。虽然劳动法上写着每天工作8小时，但可能是劳动法没有写好嘛。现在996公司和劳动法规定有冲突，我觉得可以有多种解决方案：
1. 996公司错了，整改
2. 劳动法错了，改劳动法，规定996合法
3. 劳动者错了，别劳动了

看，这样提出多个方案，是不是就显得更理智，更讲道理了？

2019-04-02 02:47 UTC, EarthTeenager commented
@ zxkjack123 我建议新增一条
4、地球公转一天才24小时太短了，错了，让他它多转一会儿

2019-04-02 02:54 UTC, q1045243113 commented
小米手机自带的浏览器也开始屏蔽  https://996.icu/

2019-04-02 02:55 UTC, zxkjack123 commented
> @ zxkjack123 我建议新增一条
> 4、地球公转一天才24小时太短了，错了，让他它多转一会儿

嗯，好，采纳了！

2019-04-02 02:57 UTC, EarthTeenager commented
@zxkjack123 口误，是地球自转。。。

2019-04-02 03:00 UTC, GreekPanda commented
> @ zxkjack123 我建议新增一条
> 4、地球公转一天才24小时太短了，错了，让他它多转一会儿

你们就不要抬杠了，没劲。不要陷入了一说正事，就一大堆杠精出来搅混水的状态。另外，你们也不要跟老外多逼逼，小心有轮子在带节奏了。到时候，政府怒了，管你们丫996，还是999，先把G站封了再说。所有的讨论不要扩大化，不要上纲上线，什么政治体制啥啥的，纯粹给自己挖坑。我们就是就事论事，就是看不惯那些钱给不到位，却要员工99x的垃圾公司，要讨伐他们，逼迫他们，让他们知道随意压榨自己的员工是有代价的。这样有的放矢，政府高层才会站在我们这边，要是随便跟着轮子的寄走就是另一个six-four，到头来毛线都没有，还弄得灰头土脸，狗屁不是，那就是不是我们996icu的本意了。

百无一用是书生，码农也不要把自己太当回事，现在造成的轰动效应，千万不要成为西方媒体攻击中国政体的靶子，大家生生被别人当成了枪使。最终，啥也没有，石沉大海。

2019-04-02 03:03 UTC, immortalChensm commented
现在能玩git的人多半是程序员！占的人数极少！
1、部分程序员git都不会玩，知道毛线。
2、部分程序员不懂法律。
3、国内本科学历以上的人特别少
4、国内加班严重已经是实事
5、国内IT小公司太多，制度不完善
6、国内程序员法律意识淡薄
7、国内程序员对加班已经麻木
8、国内程序员不团队，背后小人多
9、国内资本主义已经很强大
10、国内程序员没有资本和资本列强做法律斗争，更没有能力跟他们争取所谓的合法权益
11、国内资本列强资源多，程序员团队不团队力量小，无法做出任何实质性的有效措施，只能呻吟叫苦
12、天朝目前不够开放，对部分国外优秀资源依赖采取抑制，屏蔽
13、天朝都是愚民政策，更希望人傻稳定发展，有利于资本主义赚取更多的利润交税
14、天朝更偏向于资本主义，帮助他们发展企业
终上所述，国内程序员只有被宰杀！

2019-04-02 03:06 UTC, zxkjack123 commented
> 现在能玩git的人多半是程序员！占的人数极少！
> 1、部分程序员git都不会玩，知道毛线。
> 2、部分程序员不懂法律。
> 3、国内本科学历以上的人特别少
> 4、国内加班严重已经是实事
> 5、国内IT小公司太多，制度不完善
> 6、国内程序员法律意识淡薄
> 7、国内程序员对加班已经麻木
> 8、国内程序员不团队，背后小人多
> 9、国内资本主义已经很强大
> 10、国内程序员没有资本和资本列强做法律斗争，更没有能力跟他们争取所谓的合法权益
> 11、国内资本列强资源多，程序员团队不团队力量小，无法做出任何实质性的有效措施，只能呻吟叫苦
> 12、天朝目前不够开放，对部分国外优秀资源依赖采取抑制，屏蔽
> 13、天朝都是愚民政策，更希望人傻稳定发展，有利于资本主义赚取更多的利润交税
> 14、天朝更偏向于资本主义，帮助他们发展企业
> 终上所述，国内程序员只有被宰杀！

你这些论断，把程序员和git换成其他行业的名词，好像也没啥问题。

2019-04-02 03:08 UTC, xxllp commented
分配制度不科学

2019-04-02 03:16 UTC, stoneAlbert commented
建议搞一些实际的事来抵制 而不是在这个网站屏幕后随口说说 开源协议就挺好的 但一些作者不答应

2019-04-02 03:21 UTC, 2821840032 commented
@stoneAlbert 是的 我也和一些作者联系了 ，他们不同意加入这个协议。

2019-04-02 03:27 UTC, stoneAlbert commented
@2821840032  比如?

2019-04-02 03:28 UTC, qfxl commented
https://github.com/qfxl/RoundProgressBar
微薄之力

2019-04-02 03:32 UTC, hui305 commented
请大家别在这里闲聊！
自己写开源，增加影响力，或者找支持这个协议的开源人士！例如：找openresty的作者，看支持吗？
在这里打嘴炮没用！

2019-04-02 03:38 UTC, 2821840032 commented
不想说 不然好像我强制要求他们加入一样。@stoneAlbert 
有作者觉得我们做的都是无用功 只是在网上吐槽 等热度一过 却没有任何实际效果
我也有点迷茫
我觉得我能做的就是面试时甩那些996招聘者的脸

2019-04-02 03:58 UTC, feng-wuhan-007 commented
星星之火，可以燎原，权利是需要不断争取的，为发起这个项目的作者点赞，希望就在前面，努力就有希望。

2019-04-02 04:32 UTC, hui305 commented
大家小心有人在电报群大谈政治。我们不能被这些人带偏了节奏！这些人不知道是何居心！
我们争取程序员的合法权益！其他不要多谈，不要被人带了节奏，这些人用心险恶！

2019-04-02 04:53 UTC, AFeyman commented
相比996，我单双休，朝9晚5:30,还是可以接受的，只是算起来一周还是多上了2小时，没加班工资不说，还没调休

2019-04-02 05:10 UTC, jieend commented
> 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996

做得好，我也是去年离开了996的前东家，人不但不能作恶，而且不能助纣为虐，公司搞996，你不进行抵制，无形中会助长资本家的嚣张气焰。你不坚决的抵制996，也许我们的子女会世世代代为奴，这不是一句空话！

2019-04-02 06:34 UTC, WYHSummer commented
> > 现在能玩git的人多半是程序员！占的人数极少！
> > 1、部分程序员git都不会玩，知道毛线。
> > 2、部分程序员不懂法律。
> > 3、国内本科学历以上的人特别少
> > 4、国内加班严重已经是实事
> > 5、国内IT小公司太多，制度不完善
> > 6、国内程序员法律意识淡薄
> > 7、国内程序员对加班已经麻木
> > 8、国内程序员不团队，背后小人多
> > 9、国内资本主义已经很强大
> > 10、国内程序员没有资本和资本列强做法律斗争，更没有能力跟他们争取所谓的合法权益
> > 11、国内资本列强资源多，程序员团队不团队力量小，无法做出任何实质性的有效措施，只能呻吟叫苦
> > 12、天朝目前不够开放，对部分国外优秀资源依赖采取抑制，屏蔽
> > 13、天朝都是愚民政策，更希望人傻稳定发展，有利于资本主义赚取更多的利润交税
> > 14、天朝更偏向于资本主义，帮助他们发展企业
> > 终上所述，国内程序员只有被宰杀！
> 
> 你这些论断，把程序员和git换成其他行业的名词，好像也没啥问题。但第13条我觉得不妥，国内还是很重视教育的，很多人是愚民，还真不全是天朝的锅。

哎，还是没有资本争取自己的合法权利，国内法律也不健全！毕竟不能饿死自己呀！

2019-04-02 06:51 UTC, MnyZhao commented
还好我顺利脱坑了

2019-04-02 06:57 UTC, caiwilliam commented
自己想要过什么样的生活，就要自己去争取，为了这个目标奋斗，而不是等着别人来帮你实现，每个人的一小步，最终会变成一大步；只要力所能及，就算只是知道这个事情，也算一小步

2019-04-02 07:00 UTC, szhielelp commented
![image](https://user-images.githubusercontent.com/10084666/55382328-f7d5a400-5557-11e9-9b42-8ea1a01ab657.png)
微薄之力

2019-04-02 07:00 UTC, CN-YUANYU commented
互联网版的工人运动

2019-04-02 07:30 UTC, bairenxing commented
脑力劳动者一天能集中精力工作的时间并不是很长，996工作制肯定不是合理高效的，这对员工的身体以及家庭都不利。

2019-04-02 07:31 UTC, Jvongo commented
无论最后成不成功，都是一种思想启蒙

2019-04-02 07:47 UTC, skyoxZ commented
固然996令人深恶痛绝，然而，我认为这个“反996”许可协议是有问题的。试想，某个开源软件规定使用者不得抱有地域歧视、必须尊重别人的性取向、不得用于军事领域……这本身违背了自由软件的精神。

2019-04-02 08:01 UTC, bunnyblueair commented
https://github.com/bunnyblueair/AntiVM 微薄之力

2019-04-02 09:07 UTC, yyrdl commented
> 固然996令人深恶痛绝，然而，我认为这个“反996”许可协议是有问题的。试想，某个开源软件规定使用者不得抱有地域歧视、必须尊重别人的性取向、不得用于军事领域……这本身违背了自由软件的精神。

劳动者权益 是基本的权利，这在哪个国家都是基本共识，而性取向、宗教这类就不是共识了， 所以还是存在区别的，个人认为这并不违反自由软件精神，反而是一个恰当的补充，是积极的

2019-04-02 09:18 UTC, hwgeone commented
> > 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996
> 
> 同意。自己的权利要自己去争取，而不是妥协**卑微地** 迁就，**懦弱地**退缩。正式那些为了为己在老板面前装好人的奸邪小人的迁就那些老板，造成了加班制度陷入了一个恶性循环：你不加班，你滚，有的是劳动力。同时，一个公司实行加班制度，其他公司也会效仿。
> 
> 说白了还是廉价劳动力供远大于求

分析的很好。这个协议如果生效了，那么将是人类的万幸。

2019-04-02 09:47 UTC, angus008 commented
> 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996

兄弟哪个辣鸡公司，说说呗

2019-04-02 11:12 UTC, L-uncle commented
（以后去面试可能就会多一个问题）
(There may be one more question in the interview later.)
面试官：很好，你的简历是很出彩，我想再问你个问题，好吗？
Interviewer :  Fine. Your resume is excellent. I'd like to ask you another question, OK?
应聘者：好，您请问。
Interviewee :  OK, please.
面试官：你对996事件怎么看？简单谈谈你的看法！
Interviewer :  What do you think of the 996 incident? Briefly talk about your opinion!
应聘者：。。。。。。。。。
Applicant :    ...
哈哈

2019-04-02 12:06 UTC, northlion commented
> 我因反对公司长期996加班 并且反对国企节加班在群里跟同事们说 明天都不要去加班了.一个个答应说不想加班 背后却有奸邪小人打报告给老板,老板让我第二天写个辞职申请.我走的时候就说了一句 早晚都有这么一天 我只不过是早走而已.一群没有血性的人 不但不去争取自己权利反而打小报告.现在本人965不加班 工资只比996少1k 但是小时工资却高了不少 我希望前公司早点倒闭 做996killer 消灭一切996

这种人在过去被称之为工贼（大概意思就是工人内部的叛徒，资本家的走狗）

2019-04-02 12:12 UTC, bugithubUser commented
> （以后去面试可能就会多一个问题）
> (There may be one more question in the interview later.)
> 面试官：很好，你的简历是很出彩，我想再问你个问题，好吗？
> Interviewer : Fine. Your resume is excellent. I'd like to ask you another question, OK?
> 应聘者：好，您请问。
> Interviewee : OK, please.
> 面试官：你对996事件怎么看？简单谈谈你的看法！
> Interviewer : What do you think of the 996 incident? Briefly talk about your opinion!
> 应聘者：。。。。。。。。。
> Applicant : ...
> 哈哈

老实说即可吧？风往955这边刮的话不就胜利了吗

2019-04-02 12:46 UTC, ohhhhyaa commented
希望我们共同努力把反996工作制度规则从新写一遍，这样能够扩大除了我们国家其他国家的反996的影响力，而不是仅仅局限于我们国家的劳动法

2019-04-02 12:59 UTC, hui305 commented
本群不谈政治，争取和维护程序员的权益！也欢迎学法律的同学加入！
本群的目标：在广大的程序员之间达成共识，形成一种反996的文化！反对无情的剥削和压榨！
只要不谈政治，大家畅所欲言！电报群：https://t.me/oppose996

2019-04-02 13:23 UTC, iericzhu commented on README.md
> +- this is not a politic activity,we are the staunch supporters of labour law. we ask employers to respect the legitimate rights and interests of employees.
ask -> demand

2019-04-02 13:31 UTC, ShuaiShuaiLee commented
不谈政治，合理抗议！要不要会被封了的！

2019-04-02 16:02 UTC, Findaaron commented
在坚定维护劳动法的框架下，维护劳动者的合法权益，加油。

2019-04-02 17:25 UTC, sevenyq commented
就应该这样，在996名单上的公司，不然他用

2019-04-03 03:01 UTC, blueSkyLoop commented
值得庆幸的是，我的头发还是挺浓密的；
就是肩颈越来越严重....
为什么开发周期却要算上加班时间去排期？
为什么改需求却不想想问题的根源在哪里？
为什么出了质量问题都是我们的锅？
我们也只是一个有血有肉的普通人，并不是机器人。😊

2019-04-03 03:10 UTC, blueSkyLoop commented
值得庆幸的是，我的头发还是挺浓密的；
就是肩颈越来越严重....
为什么开发周期却要算上加班时间去排期？
为什么改需求却不想想问题的根源在哪里？
为什么出了质量问题都是我们的锅？
4.1号那天我带着病加班到11点多，结果4.2号发烧不得不请假，接了好几次上级的电话，打着点滴，拿着电脑继续开干。
别人怕背锅，我们却在卖命，
我们也只是一个有血有肉的普通人，还是努力点别让自己的后代踏进IT行业吧。😊

2019-04-03 04:43 UTC, ykla commented
建议加入GNU计划

2019-04-03 04:53 UTC, Naville commented
> 就应该这样，在996名单上的公司，不然他用
相信我这些star不超过个位数的项目没有公司想用，别太高看自己的水平了

2019-04-03 05:42 UTC, EpisodeOnly commented
这种事情，一定要支持一下

2019-04-03 07:28 UTC, kiann commented
> 小米手机自带的浏览器也开始屏蔽 https://996.icu/

目前小米手机自带浏览器的访问已经恢复，不知道背后是什么博弈

2019-04-03 08:25 UTC, nickHsiung commented
3.26 《劳动协议保护日》

2019-04-03 09:15 UTC, mgsky1 commented
如果能拉到Apache，Spring等组织的支持的话就再好不过了😄

2019-04-03 11:35 UTC, closed without merging

2019-04-19 03:01 UTC, akeliduo commented
建议反996协议增加中文版本，如果协议仅仅用英文，那么使用英文的程序员即使引入了该协议，但是对国内的影响其实不大，因为还有一大部分中文程序员其实是不怎么看英文协议的；但如果加入了中文协议，则和英文协议一起要求写在支持的软件代码中，这样引用起来就可以增加传播，真正达到维护程序员的切身利益。