添加公司作恶行为名单
996icu/996.ICU pull request #24893
Opened 2019-04-02 03:40 UTC by wedao1

基于腾讯、360等公司封禁本项目而作出的反应。

2019-04-02 03:49 UTC, binarywang commented
赞

2019-04-02 03:51 UTC, Bright99 commented
牛B

2019-04-02 03:52 UTC, mofeiren commented
360才是真的恶心

2019-04-02 03:55 UTC, nickHsiung commented
360不知道为什么不倒闭

2019-04-02 04:04 UTC, yiranleng commented
UC浏览器屏蔽了网站

2019-04-02 04:10 UTC, vmjcv commented
夸克浏览器屏蔽了网站

2019-04-02 04:11 UTC, zhuxiaoxi commented
你的`.DS_Store`都提交进来了，建议添加到全局忽略文件里面
```
git config --global core.excludesfile ~/.gitignore; echo .DS_Store >> ~/.gitignore
```

2019-04-02 04:15 UTC, TheMasterOfMagic requested changes
.DS_Store目录不应该被提交

2019-04-02 04:39 UTC, icu996 commented
当瞒而不报变成了一种行政手段，并美其名曰“维稳”时。长期来看，“维稳”被滥用的风险就不断扩大，欺上瞒下就会成为必然的结果。最终上不知下，下不通上，胡作非为可能更加严重，那社会的稳定岂不是无从谈起？

2019-04-02 04:42 UTC, andriyhuang commented
微信和QQ均已经屏蔽了本项目访问.....

2019-04-02 04:44 UTC, yiranleng commented
压榨人民的刽子手

2019-04-02 04:48 UTC, ju0594 commented
小米浏览器已屏蔽该项目地址

2019-04-02 04:53 UTC, wedao1 commented
已经重新pr，删除了不必要的文件。 https://github.com/996icu/996.ICU/pull/24904

2019-04-02 04:55 UTC, weiyaoxing commented
360急速浏览器

2019-04-02 05:07 UTC, L-stiven commented
除了无耻不知道该说点啥~

2019-04-02 05:21 UTC, TheMasterOfMagic commented
> 已经重新pr，删除了不必要的文件。 #24904

原来的这个pr可以关闭了

2019-04-02 05:22 UTC, closed without merging

2019-04-02 08:24 UTC, DenisWW commented
搜狗这个垃圾也屏蔽了

2019-04-02 08:27 UTC, sk95120 commented
> 搜狗这个垃圾也屏蔽了
搜狗互联网里的“养老”公司，加班不严重啊。

2019-04-02 09:29 UTC, yan-gong commented
chrome  可以

2019-04-02 09:36 UTC, Lyongwang commented
就在昨天，愚人节开启了996的时代

2019-04-02 09:39 UTC, Lyongwang commented
大易车

2019-04-02 09:42 UTC, Songzanganbu commented
### 易车互联

2019-04-04 12:37 UTC, zhengweisk commented
狗日的资本主义。把程序员当畜生一样用。劳动法以及每周工作40个小时是用鲜血换来的！

2019-04-05 04:23 UTC, LongfuSpring commented
周六光明正大的要求上班
![1](https://user-images.githubusercontent.com/49298978/55603514-a159a700-579d-11e9-985c-b715881ebbd2.jpg)

2020-06-15 09:54 UTC, Puzzlerer commented
刚刚手机上下载了UC浏览器，发现导致手机无法翻墙，也无法访问google，真是可悲